### ISSUE TITLE
White Screen on boot

### ISSUE THREAD

**Issue by anonaii** [Robz8/TWiLightMenu#221]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 2DS
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release _[6.2.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[2.0.2]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

I don't know, I was hoping for a ROM selection screen or something

### Actual behaviour

The program opens up, it shows me the options and everything. When I tap "Start DSiMenu++" it shows me the DS boot screen, then it shows me a DSiMenu boot screen, and then it just stays white. I've let it sit for about 5 minutes and it just stays white

### Steps to reproduce

1.Follow the wiki instructions
2.Open DSiMenu++ Launcher
3.Click Start DSiMenu++

**Comment by anonaii** [comment]
On the bright side the rainbow led works

**Comment by takeshineale128** [comment]
I have this issue also. it will white screen on 0.12 bootstrap but not 0.11.2 bootstrap. PS all my systems are European.

**Comment by Robz8** [comment]
@anonaii Do you have these files in `sd:/_nds`?
* dsimenu.srldr
* r4menu.srldr
* akmenu.srldr

If you do, try reformatting your SD card.

**Comment by anonaii** [comment]
@takeshineale128 My system is USA
@Robz8 I only have `nds-bootstrap.ini` and `dsimenuplusplus/`

**Comment by Robz8** [comment]
Oh, I mean those files in `sd:/_nds/dsimenuplusplus`.

**Comment by anonaii** [comment]
Aha! I got to the ROM selection menu, went to my `roms/` folder, and tried to run NSMB and Pokemon Black (Got them off of romsmania) and when I try to run them, I get
```
Creating save file.
Start failed. Error 1
```

**Comment by Robz8** [comment]
You need the nds-bootstrap files, which go in `sd:/_nds`.

**Comment by anonaii** [comment]
All of them, or just the ones marked with release?

**Comment by anonaii** [comment]
Now it's showing a white screen when I boot it, no (visible) errors. Tell me honestly, am I an idiot?

**Comment by anonaii** [comment]
Now it's showing a white screen when I go press play, no (visible) errors.
Tell me honestly, am I an idiot?

**Comment by Robz8** [comment]
No. The nds-bootstrap version included with DSiMenu++ doesn't work correctly for some reason.
Try [this](https://github.com/Robz8/TWiLightMenu-update/raw/96d4ed5db5320f9a056d397cd34445d746db93e6/nds-bootstrap-nightly.nds) build, and set it to nightly.

**Comment by anonaii** [comment]
Set what to nightly?

**Comment by Robz8** [comment]
I edited my post.

**Comment by anonaii** [comment]
Ah, works perfectly, thanks! One last off-topic question, how do I have my notification LED always shine rainbow?

**Comment by Robz8** [comment]
Set the LED in CTR mode settings in the Launcher, to rainbow

**Comment by anonaii** [comment]
I mean even after I shut down DSiMenu, I've heard of a program called MCUBricker but I can't find any links to it
