### ISSUE TITLE
Guru Meditation Error when Starting DSiMenu++

### ISSUE THREAD

**Issue by pjcrary** [Robz8/TWiLightMenu#224]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [✓]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [✓]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [✓]  Release v2.0.2
- [ ]  Nightly

### TWiLight Menu++ version

Tell us which versions you are using:

- [✓]  Release v6.2.1
- [ ]  Nightly
### Expected behaviour

Load DSiMenu++

### Actual behaviour

When tapping "Start DSiMenu++", it displays a Guru Meditation Error.

### Steps to reproduce

1. Launch the DSiMenu++ Launcher
2. Tap "Start DSiMenu++"

This happened just today, I have had no problems before. (My theme is Acekard Dark if that helps)

**Comment by Robz8** [comment]
Acekard theme is kinda buggy for some users.
Try switching out of it by holding start during the DSiMenu++ splash.

**Comment by pjcrary** [comment]
Thank you for the help! It started working when switching to the DSi theme!
