### ISSUE TITLE
Red loading pong (WITH LOGS)

### ISSUE THREAD

**Issue by GWTRC** [Robz8/TWiLightMenu#225]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

(I'm using DSiMenu++)

### Expected behaviour

Tell us what should happen
I should be able to load Mario Kart DS (NoSSL patched)
### Actual behaviour

Tell us what happens instead
I load Mario Kart DS, I get the Pong load screen, and it goes red.
### Steps to reproduce

1. Load Mario Kart DS from the SD Card
2. Wait
Here's the log:

patchCardNds

findCardReadEndOffsetThumb:
ARM9 Card read end thumb not found

findCardReadEndOffsetType0:
ARM9 Card read end (type 0) not found

findCardReadEndOffsetType1:
ARM9 Card read end alt (type 1) not found

ERR_LOAD_OTHR

findSleepPatchOffset:
Sleep patch not found

Trying thumb...
findSleepPatchOffsetThumb:
Thumb sleep patch thumb not found
Thumb sleep patch thumb alt not found

findCardIrqEnableOffset:
irq enable not found
irq enable alt not found

ERR_NONE  
debug: true
ndsPath: "sd:/roms/nds/MKDS.nds"
savPath: "sd:/roms/nds/MKDS.sav"
saveSize: 80000
language: FF
dsiMode: false
donorSdkVer: 0
patchMpuRegion: 0
patchMpuSize: 0
consoleModel: 0
loadingScreen: 2
romread_LED: 3
boostCpu: false
gameSoftReset: false
asyncPrefetch: false
soundFix: false
logging: true
initDisc: true
dldiPatchNds: true
argc: 1
cheat_data_len: 0
backlightMode: 0

**Comment by GWTRC** [comment]
I couldn't work out how to make all of the lines code, sorry

**Comment by NightYoshi370** [comment]
This has to do with nds-bootstrap
Closed
