### ISSUE TITLE
CIAS install, but don't appear on the System Menu, can manually launch with FBI

### ISSUE THREAD

**Issue by OldGnashburg** [Robz8/TWiLightMenu#228]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Release _[TWiLight Menu++ Launcher v.6.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[TWiLight Menu++ v.6.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When I install the two .cia files included with the release via FBI, they should appear on the System Menu to launch.

### Actual behaviour

When install the two .cia files included with the release via FBI, they do not appear in the System Menu to launch. However I can manually Launch the software from FBI's Title option.

### Steps to reproduce

1. Put TWiLight files on SD Card, however, instead of copying the cia folder where you put the .cia files on SD root, I just drag and drop the .cia files in my cias folder on my SD root.
2. Open FBI and install the .cia files.
3. Exit FBI and see that no titles have shown up.

**Comment by Robz8** [comment]
You didn't install the TWiLightMenu++ Launcher.
Please install it to run TWiLight Menu++ on 3DS, and for it to work correctly on 3DS.

**Comment by OldGnashburg** [comment]
That makes slightly more sense. I think it might be helpful to mention that you need the Launcher to boot off the System Menu, which is in an entirely separate repo. And that the .cia files included don't install onto System Menu. But I will close this.
