### ISSUE TITLE
Feature Request: Add which bootstrap to use to individual game settings (select button menu)

### ISSUE THREAD

**Issue by YYoshi241** [Robz8/TWiLightMenu#230]
Since we can already select DS/DSi mode, CPU speed, and VRAM Boost, and more PER GAME.
Why couldn't we do this with nds bootstrap type? (Just an idea)

**Comment by Barawer** [comment]
You mean bootstrap version?

**Comment by piratesephiroth** [comment]
there are only 2 bootstrap types, one for games and one for homebrews.

**Comment by NightYoshi370** [comment]
What @piratesephiroth said, plus the fact that they are automatically detected leads us to reject your suggestion. Sorry
