### ISSUE TITLE
Multiplayer Test

### ISSUE THREAD

**Issue by lenix9090** [Robz8/TWiLightMenu#231]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [X ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by lenix9090** [comment]
Hello! I do not know ANYTHING about editing this type of programs, but ... I have an idea. Use a system similar to Ni-Fi (the multiplayer that uses the NES emulator) as an option in the configuration to replace wireless DS communication and play multiplayer in games like New Super Mario Bros or Welcome To Animal Croosing Wild World. Thank you! PS: Is it possible?

Google translator

**Comment by lenix9090** [comment]
* If you speak Spanish, it will be easier to make me understand

**Comment by lenix9090** [comment]
¡Hola! No sé NADA sobre la edición de este tipo de programas, pero ... Tengo una idea. Use un sistema similar al Ni-Fi (el multijugador que usa el emulador NES) como una opción en la configuración para reemplazar la comunicación inalámbrica DS y jugar al modo multijugador en juegos como New Super Mario Bros o Welcome To Animal Croosing Wild World. ¡Gracias! PD: ¿Es posible?

**Comment by Robz8** [comment]
idk how Ni-Fi works,
