### ISSUE TITLE
White screen with 6.3.0 on DSi XL

### ISSUE THREAD

**Issue by mbj222** [Robz8/TWiLightMenu#235]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [X]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release v6.3.0
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

After the custom splashscreen (set by me) show up, the console should boot up and show DSiMenu++/TWiLightMenu own icon or splashscreen

### Actual behaviour

After the custom splashscreen (set by me) show up, both the screens remain white and, after 3 seconds, the wi-fi led turn on. The only way to shutdown the console is to keep pressing the power button.

### Steps to reproduce

1. Press the power button.
2. Wait for the custom splashscreen to disappear.
3. White screen.
4. Wi-Fi led turns on.
5. Still white screen.

**Comment by SimonBaars** [comment]
Have you tried deleting the "_nds" folder and then adding it again from the TWiLightMenu zip?

**Comment by mbj222** [comment]
Tried it right now and didn't solve anything, the problem is still the same.

**Comment by lenix9090** [comment]
Delete ALL the files referring to Twilight Menu Then add them all from the .zip and then add: Games, Appgen and Boxart.

Google translator

**Comment by mbj222** [comment]
So, replacing the entire _nds folder, the autoboot.bin for Hiya, the title folder from CFW - SDNAND root, the DSiWare software in the dsiware folder, the roms folder and the BOOT.NDS file fixed the problem.
Thank you.
