### ISSUE TITLE
ROMs ERROR

### ISSUE THREAD

**Issue by lenix9090** [Robz8/TWiLightMenu#237]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [*]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [* ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by dubbz82** [comment]
This should be closed until if/when the template is filled in to describe the problem

**Comment by lenix9090** [comment]
This IS completely necessary ... Before (6.0.1) I could play DBZ Super Sonic Warriors 2 (EUR) Naruto Shippueden Shinobi Retsuden 3, Jump Ultimate Stars, and more ... Now (6.0.3) I CAN NOT PLAY DBZSW2 WELL FOR ERRORS OF TEXTURES, NSSR3 HANG IN HISTORY MODE AND JUS ALSO! If ...Now Super Mario 64 has fewer errors but ... it's not worth it to damage MANY games for 1 or 2 ... Thanks and help ...



Google translator

**Comment by lenix9090** [comment]
Seriously, I'm sorry ... Only my Internet connection fell FAIR by adding the error

Google translator

**Comment by Robz8** [comment]
You need HiyaCFW installed.
The one time we got nds-bootstrap working without HiyaCFW, was a lucky chance.

**Comment by lenix9090** [comment]
@Robz8 Yes, but in 6.0.1 All this ... It was fine ... But since I updated it ... ALL that changed ... I only say it because I do not think I'm the only one that happens ... and already...

Google translator

**Comment by Robz8** [comment]
Just use HiyaCFW. You won't lose anything by installing it.
Chances of nds-bootstrap working on an upcoming version are slim to none, and using HiyaCFW is the only way to get around this issue.

**Comment by lenix9090** [comment]
@Robz8 Yes ... But My DSi is hacked with TWNLF and according to a friend when adding HiyaCFW with TWNLF is bad for the nand apart ... If now I open SUDOKU (which was where I installed everything) This Twilight Menu ++ How would you install it Any other thing?

Google translator

**Comment by Robz8** [comment]
You can use TWiLight Menu++ with Sudoku. Works fine there.

**Comment by lenix9090** [comment]
And that's what I do ... It's just that mistake that makes me crazy, and since I do not know much about this, I'm confused

**Comment by Robz8** [comment]
Do you have VRAM boost on?
If so, try turning that off.

**Comment by lenix9090** [comment]
O_o Forgive My Ignorance but ... Like that?

**Comment by lenix9090** [comment]
*What do you mean?

**Comment by Robz8** [comment]
It's in the settings screen of TWiLight Menu++.

**Comment by lenix9090** [comment]
Is turned off...
